
/*
Static strings for working with application SQL database
*/

"use strict";

/* Object containing static names of all SQL tables and fields */
const statics = {

  table_AppScope : "AppScope",
  table_AppUser_AppScope : "AppUser_AppScope",
  table_Article : "Article",
  table_ArticleFollow : "ArticleFollow",
  table_Article_Category : "Article_Category",
  table_Article_Contributor : "Article_Contributor",
  table_Article_Tag : "Article_Tag",
  table_Category : "Category",
  table_Comment : "Comment",
  table_Connection : "Connection",
  table_ContentDraft : "ContentDraft",
  table_ContentImageType : "ContentImageType",
  table_ContentImage : "ContentImage",
  table_Contributor : "Contributor",
  table_DeviceInfo : "DeviceInfo",
  table_AppUser : "AppUser",
  table_AppUser_Category : "AppUser_Category",
  table_AppUser_Fave : "AppUser_Fave",
  table_AppUser_Like : "AppUser_Like",
  table_AppUser_Save : "AppUser_Save",
  table_AppUser_Tag : "AppUser_Tag",
  table_Follow : "Follow",
  table_ContentImage : "ContentImage",
  table_LeadersExchangeEmail : "LeadersExchangeEmail",
  table_Message : "Message",
  table_MessageReadState : "MessageReadState",
  table_PasswordReset : "PasswordReset",
  table_ProfileBackgroundImage : "ProfileBackgroundImage",
  table_RefreshToken : "RefreshToken",
  table_ResourcePack : "ResourcePack",
  table_Tag : "Tag",
  table_Thread : "Thread",
  table_ThreadParticipant : "ThreadParticipant",
  table_UserRole : "UserRole",
  table_UserRole_AppScope : "UserRole_AppScope",


  col_accessRole : "accessRole",
  col_age : "age",
  col_apnsToken : "apnsToken",
  col_excerpt : "excerpt",
  col_apnsActive : "apnsActive",
  col_articleId : "articleId",
  col_audioIdentifier : "audioIdentifier",
  col_authorId : "authorId",
  col_background : "background",
  col_backgroundURL : "backgroundURL",
  col_bio : "bio",
  col_blacklisted : "blacklisted",
  col_body : "body",
  col_categoryId : "categoryId",
  col_contributorId : "contributorId",
  col_coverPhotoId : "coverPhotoId",
  col_coverSquareURL : "coverSquareURL",
  col_coverTallURL : "coverTallURL",
  col_covenantAgreed : "covenantAgreed",
  col_createdAt : "createdAt",
  col_dateOfBirth : "dateOfBirth",
  col_deletedAt : "deletedAt",
  col_draftType : "draftType",
  col_email : "email",
  col_emailVerified : "emailVerified",
  col_facebookProfileId : "facebookProfileId",
  col_fcmToken : "fcmToken",
  col_fullText : "fullText",
  col_id : "id",
  col_imageId : "imageId",
  col_imageType : "imageType",
  col_instagramUsername : "instagramUsername",
  col_isProfileBackground : "isProfileBackground",
  col_issuedAt : "issuedAt",
  col_issuedTo : "issuedTo",
  col_jsonContent : "jsonContent",
  col_lastUsed : "lastUsed",
  col_leadersExchange : "leadersExchange",
  col_linkedInProfile : "linkedInProfile",
  col_location : "location",
  col_messageId : "messageId",
  col_modelName : "modelName",
  col_name : "name",
  col_niceName : "niceName",
  col_niceTitle : "niceTitle",
  col_password : "password",
  col_pendingPublish : "pendingPublish",
  col_photo : "photo",
  col_photoCredit : "photoCredit",
  col_profileBackground : "profileBackground",
  col_profileBackgroundId : "profileBackgroundId",
  col_profileComplete : "profileComplete",
  col_publishAt : "publishAt",
  col_publishedId : "publishedId",
  col_readAt : "readAt",
  col_relationship : "relationship",
  col_resourcePackId : "resourcePackId",
  col_roleId : "roleId",
  col_scopeId : "scopeId",
  col_senderId : "senderId",
  col_sentAt : "sentAt",
  col_squarePath : "squarePath",
  col_systemName : "systemName",
  col_tagId : "tagId",
  col_tallPath : "tallPath",
  col_text : "text",
  col_threadId : "threadId",
  col_timeToReadOrWatch : "timeToReadOrWatch",
  col_title : "title",
  col_token : "token",
  col_twitterScreenName : "twitterScreenName",
  col_UDID : "UDID",
  col_updatedAt : "updatedAt",
  col_url : "url",
  col_userId : "userId",
  col_username : "username",
  col_userOneId : "userOneId",
  col_userOneId : "userOneId",
  col_userTwoId : "userTwoId",
  col_userTwoId : "userTwoId",
  col_vendorUUID : "vendorUUID",
  col_videoIdentifier : "videoIdentifier",
  col_website : "website",
  col_zipCode : "zipCode",

  val_pendingFirstSecond : "pending_first_second",
  val_pendingSecondFirst : "pending_second_first",
  val_friends : "friends",
  val_declinedFirstSecond : "declined_first_second",
  val_declinedSecondFirst : "declined_second_first",
  val_ascending : "ASC",
  val_descending : "DESC",

  get updateUserProfileColumns() {
    return [
      // this.col_email,
      this.col_name,
      // this.col_dateOfBirth,
      this.col_zipCode,
      this.col_location,
      this.col_bio,
      this.col_photo,
      this.col_profileBackgroundId
    ]
  },

  //Return columns of User table that should be in the profile
  //of a user the current user is viewing
  get userProfileColumns() {
    return [
      this.col_id,
      this.col_username,
      this.col_name,
      this.col_dateOfBirth,
      this.col_zipCode,
      this.col_location,
      this.col_bio,
      this.col_photo,
      this.col_profileBackgroundId
    ]
  },

  //Return columns of User table that should be in
  //a user's own instance
  get userColumns() {
    return [
      this.col_id,
      this.col_username,
      this.col_name,
      this.col_email,
      this.col_emailVerified,
      this.col_dateOfBirth,
      this.col_zipCode,
      this.col_location,
      this.col_bio,
      this.col_photo,
      this.col_profileComplete,
      this.col_covenantAgreed,
      this.col_profileBackgroundId,
      this.col_createdAt,
      this.col_updatedAt
    ]
  },
}

module.exports = statics;
